// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    room_id,
    sender_id,
    sender_type,
    kind,
    status,
    text,
    media_url,
    sticker_id,
    stream_id,
    sequence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
`

type CreateMessageParams struct {
	RoomID     pgtype.UUID
	SenderID   pgtype.UUID
	SenderType string
	Kind       string
	Status     string
	Text       pgtype.Text
	MediaUrl   pgtype.Text
	StickerID  pgtype.Text
	StreamID   pgtype.Text
	Sequence   pgtype.Int8
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.RoomID,
		arg.SenderID,
		arg.SenderType,
		arg.Kind,
		arg.Status,
		arg.Text,
		arg.MediaUrl,
		arg.StickerID,
		arg.StreamID,
		arg.Sequence,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MediaUrl,
		&i.StickerID,
		&i.StreamID,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTextMessage = `-- name: CreateTextMessage :one
INSERT INTO messages (
    room_id,
    sender_id,
    sender_type,
    kind,
    status,
    text,
    stream_id,
    sequence
) VALUES (
    $1, $2, $3, 'TEXT', 'SENT', $4, $5, $6
)
RETURNING id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
`

type CreateTextMessageParams struct {
	RoomID     pgtype.UUID
	SenderID   pgtype.UUID
	SenderType string
	Text       pgtype.Text
	StreamID   pgtype.Text
	Sequence   pgtype.Int8
}

func (q *Queries) CreateTextMessage(ctx context.Context, arg CreateTextMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createTextMessage,
		arg.RoomID,
		arg.SenderID,
		arg.SenderType,
		arg.Text,
		arg.StreamID,
		arg.Sequence,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MediaUrl,
		&i.StickerID,
		&i.StreamID,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
FROM messages
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MediaUrl,
		&i.StickerID,
		&i.StreamID,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
FROM messages
WHERE room_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByRoomParams struct {
	RoomID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderType,
			&i.Kind,
			&i.Status,
			&i.Text,
			&i.MediaUrl,
			&i.StickerID,
			&i.StreamID,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByUserID = `-- name: ListMessagesByUserID :many
SELECT id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
FROM messages
WHERE sender_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMessagesByUserIDParams struct {
	SenderID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListMessagesByUserID(ctx context.Context, arg ListMessagesByUserIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByUserID, arg.SenderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderType,
			&i.Kind,
			&i.Status,
			&i.Text,
			&i.MediaUrl,
			&i.StickerID,
			&i.StreamID,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages
SET
    status = 'DELETED',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MediaUrl,
		&i.StickerID,
		&i.StreamID,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMessageStatus = `-- name: UpdateMessageStatus :one
UPDATE messages
SET
    status = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
`

type UpdateMessageStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageStatus, arg.ID, arg.Status)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MediaUrl,
		&i.StickerID,
		&i.StreamID,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
