// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messages
SET
    status = 'DELETED',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const findAllMessagesByRoom = `-- name: FindAllMessagesByRoom :many
SELECT id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
FROM messages
WHERE room_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type FindAllMessagesByRoomParams struct {
	RoomID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) FindAllMessagesByRoom(ctx context.Context, arg FindAllMessagesByRoomParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, findAllMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderType,
			&i.Kind,
			&i.Status,
			&i.Text,
			&i.MediaUrl,
			&i.StickerID,
			&i.StreamID,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllMessagesByUserID = `-- name: FindAllMessagesByUserID :many
SELECT id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
FROM messages
WHERE sender_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindAllMessagesByUserIDParams struct {
	SenderID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) FindAllMessagesByUserID(ctx context.Context, arg FindAllMessagesByUserIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, findAllMessagesByUserID, arg.SenderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderType,
			&i.Kind,
			&i.Status,
			&i.Text,
			&i.MediaUrl,
			&i.StickerID,
			&i.StreamID,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMessageByID = `-- name: FindMessageByID :one
SELECT id, room_id, sender_id, sender_type, kind, status, text, media_url, sticker_id, stream_id, sequence, created_at, updated_at, deleted_at
FROM messages
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) FindMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, findMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.Kind,
		&i.Status,
		&i.Text,
		&i.MediaUrl,
		&i.StickerID,
		&i.StreamID,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
    room_id,
    sender_id,
    sender_type,
    kind,
    status,
    text,
    media_url,
    sticker_id,
    stream_id,
    sequence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertMessageParams struct {
	RoomID     pgtype.UUID
	SenderID   pgtype.UUID
	SenderType string
	Kind       string
	Status     string
	Text       pgtype.Text
	MediaUrl   pgtype.Text
	StickerID  pgtype.Text
	StreamID   pgtype.Text
	Sequence   pgtype.Int8
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.RoomID,
		arg.SenderID,
		arg.SenderType,
		arg.Kind,
		arg.Status,
		arg.Text,
		arg.MediaUrl,
		arg.StickerID,
		arg.StreamID,
		arg.Sequence,
	)
	return err
}

const insertTextMessage = `-- name: InsertTextMessage :exec
INSERT INTO messages (
    room_id,
    sender_id,
    sender_type,
    kind,
    status,
    text,
    stream_id,
    sequence
) VALUES (
    $1, $2, $3, 'TEXT', 'SENT', $4, $5, $6
)
`

type InsertTextMessageParams struct {
	RoomID     pgtype.UUID
	SenderID   pgtype.UUID
	SenderType string
	Text       pgtype.Text
	StreamID   pgtype.Text
	Sequence   pgtype.Int8
}

func (q *Queries) InsertTextMessage(ctx context.Context, arg InsertTextMessageParams) error {
	_, err := q.db.Exec(ctx, insertTextMessage,
		arg.RoomID,
		arg.SenderID,
		arg.SenderType,
		arg.Text,
		arg.StreamID,
		arg.Sequence,
	)
	return err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    status = $2,
    text = $3,
    media_url = $4,
    sticker_id = $5,
    stream_id = $6,
    sequence = $7,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateMessageParams struct {
	ID        pgtype.UUID
	Status    string
	Text      pgtype.Text
	MediaUrl  pgtype.Text
	StickerID pgtype.Text
	StreamID  pgtype.Text
	Sequence  pgtype.Int8
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage,
		arg.ID,
		arg.Status,
		arg.Text,
		arg.MediaUrl,
		arg.StickerID,
		arg.StreamID,
		arg.Sequence,
	)
	return err
}
