// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID         pgtype.UUID
	RoomID     pgtype.UUID
	SenderID   pgtype.UUID
	SenderType string
	Kind       string
	Status     string
	Text       pgtype.Text
	MediaUrl   pgtype.Text
	StickerID  pgtype.Text
	StreamID   pgtype.Text
	Sequence   pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type Room struct {
	ID                 pgtype.UUID
	Type               string
	Status             string
	Capacity           int32
	CreatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	ActivatedAt        pgtype.Timestamptz
	ClosedAt           pgtype.Timestamptz
	LastMessageAt      pgtype.Timestamptz
	LastAiIntervenedAt pgtype.Timestamptz
}

type RoomMember struct {
	RoomID            pgtype.UUID
	UserID            pgtype.UUID
	Role              string
	Status            string
	JoinedAt          pgtype.Timestamptz
	LeftAt            pgtype.Timestamptz
	LastReadMessageID pgtype.UUID
}

type User struct {
	ID                 pgtype.UUID
	Nickname           string
	AvatarUrl          pgtype.Text
	PersonalityProfile []byte
	UsagePurpose       pgtype.Text
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}
