// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :one
INSERT INTO room_members (
    room_id,
    user_id,
    role,
    status
) VALUES (
    $1, $2, $3, 'JOINED'
)
ON CONFLICT (room_id, user_id)
DO UPDATE SET
    status = 'JOINED',
    role = EXCLUDED.role,
    joined_at = now(),
    left_at = NULL
RETURNING room_id, user_id, role, status, joined_at, left_at, last_read_message_id
`

type AddRoomMemberParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, addRoomMember, arg.RoomID, arg.UserID, arg.Role)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}

const getRoomMember = `-- name: GetRoomMember :one
SELECT room_id, user_id, role, status, joined_at, left_at, last_read_message_id
FROM room_members
WHERE room_id = $1
  AND user_id = $2
`

type GetRoomMemberParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetRoomMember(ctx context.Context, arg GetRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, getRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}

const leaveRoom = `-- name: LeaveRoom :one
UPDATE room_members
SET
    status = 'LEFT',
    left_at = now()
WHERE room_id = $1
  AND user_id = $2
RETURNING room_id, user_id, role, status, joined_at, left_at, last_read_message_id
`

type LeaveRoomParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, leaveRoom, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}

const listJoinedRoomMembers = `-- name: ListJoinedRoomMembers :many
SELECT room_id, user_id, role, status, joined_at, left_at, last_read_message_id
FROM room_members
WHERE room_id = $1
  AND status = 'JOINED'
ORDER BY joined_at ASC
`

func (q *Queries) ListJoinedRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listJoinedRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.LastReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT room_id, user_id, role, status, joined_at, left_at, last_read_message_id
FROM room_members
WHERE room_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.LastReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastReadMessage = `-- name: UpdateLastReadMessage :one
UPDATE room_members
SET last_read_message_id = $3
WHERE room_id = $1
  AND user_id = $2
RETURNING room_id, user_id, role, status, joined_at, left_at, last_read_message_id
`

type UpdateLastReadMessageParams struct {
	RoomID            pgtype.UUID
	UserID            pgtype.UUID
	LastReadMessageID pgtype.UUID
}

func (q *Queries) UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, updateLastReadMessage, arg.RoomID, arg.UserID, arg.LastReadMessageID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}
