// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAllJoinedRoomMembersByRoomID = `-- name: FindAllJoinedRoomMembersByRoomID :many
SELECT room_id, user_id, role, status, joined_at, left_at, last_read_message_id
FROM room_members
WHERE room_id = $1
  AND status = 'JOINED'
ORDER BY joined_at ASC
`

func (q *Queries) FindAllJoinedRoomMembersByRoomID(ctx context.Context, roomID pgtype.UUID) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, findAllJoinedRoomMembersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.LastReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllRoomMembersByRoomID = `-- name: FindAllRoomMembersByRoomID :many
SELECT room_id, user_id, role, status, joined_at, left_at, last_read_message_id
FROM room_members
WHERE room_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) FindAllRoomMembersByRoomID(ctx context.Context, roomID pgtype.UUID) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, findAllRoomMembersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.LastReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoomMemberByRoomIDAndUserID = `-- name: FindRoomMemberByRoomIDAndUserID :one
SELECT room_id, user_id, role, status, joined_at, left_at, last_read_message_id
FROM room_members
WHERE room_id = $1
  AND user_id = $2
`

type FindRoomMemberByRoomIDAndUserIDParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) FindRoomMemberByRoomIDAndUserID(ctx context.Context, arg FindRoomMemberByRoomIDAndUserIDParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, findRoomMemberByRoomIDAndUserID, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}

const updateRoomMember = `-- name: UpdateRoomMember :one
UPDATE room_members
SET
    role = $3,
    status = $4,
    left_at = $5,
    last_read_message_id = $6
WHERE room_id = $1
  AND user_id = $2
RETURNING room_id, user_id, role, status, joined_at, left_at, last_read_message_id
`

type UpdateRoomMemberParams struct {
	RoomID            pgtype.UUID
	UserID            pgtype.UUID
	Role              string
	Status            string
	LeftAt            pgtype.Timestamptz
	LastReadMessageID pgtype.UUID
}

func (q *Queries) UpdateRoomMember(ctx context.Context, arg UpdateRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, updateRoomMember,
		arg.RoomID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.LeftAt,
		arg.LastReadMessageID,
	)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}
