// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET
    status = 'DELETED',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, nickname, avatar_url, personality_profile, usage_purpose, status, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FindAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FindAllUsers(ctx context.Context, arg FindAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, findAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.PersonalityProfile,
			&i.UsagePurpose,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, nickname, avatar_url, personality_profile, usage_purpose, status, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PersonalityProfile,
		&i.UsagePurpose,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    nickname,
    avatar_url,
    personality_profile,
    usage_purpose,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, nickname, avatar_url, personality_profile, usage_purpose, status, created_at, updated_at, deleted_at
`

type InsertUserParams struct {
	Nickname           string
	AvatarUrl          pgtype.Text
	PersonalityProfile []byte
	UsagePurpose       pgtype.Text
	Status             string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Nickname,
		arg.AvatarUrl,
		arg.PersonalityProfile,
		arg.UsagePurpose,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PersonalityProfile,
		&i.UsagePurpose,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUserWithID = `-- name: InsertUserWithID :one
INSERT INTO users (
    id,
    nickname,
    avatar_url,
    personality_profile,
    usage_purpose,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, nickname, avatar_url, personality_profile, usage_purpose, status, created_at, updated_at, deleted_at
`

type InsertUserWithIDParams struct {
	ID                 pgtype.UUID
	Nickname           string
	AvatarUrl          pgtype.Text
	PersonalityProfile []byte
	UsagePurpose       pgtype.Text
	Status             string
}

func (q *Queries) InsertUserWithID(ctx context.Context, arg InsertUserWithIDParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUserWithID,
		arg.ID,
		arg.Nickname,
		arg.AvatarUrl,
		arg.PersonalityProfile,
		arg.UsagePurpose,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PersonalityProfile,
		&i.UsagePurpose,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    nickname = $2,
    avatar_url = $3,
    personality_profile = $4,
    usage_purpose = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, nickname, avatar_url, personality_profile, usage_purpose, status, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                 pgtype.UUID
	Nickname           string
	AvatarUrl          pgtype.Text
	PersonalityProfile []byte
	UsagePurpose       pgtype.Text
	Status             string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Nickname,
		arg.AvatarUrl,
		arg.PersonalityProfile,
		arg.UsagePurpose,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PersonalityProfile,
		&i.UsagePurpose,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
