name: "機能追加リクエスト"
description: "新機能を提案する"
title: "feat: "
labels: ["feature request"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: どんな機能が欲しいか
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 背景・目的
      description: なぜこの機能が必要か / 解決したい課題
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: 方針
      description: 大まかな実装方針を記述してください（無くてもOK）
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: 完了条件
      description: この機能が「完了」と言える条件をチェックリストで
      value: |
        - [ ] 
        - [ ] 
    validations:
      required: false

