name: authz-check

on:
  push:
    branches:
      - main
    paths:
      - 'authz-service/**'
      - '.github/workflows/authz.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'authz-service/**'
      - '.github/workflows/authz.yaml'

jobs:
  authz:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: authz-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: authz-service/go.mod

    - name: Check go mod tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: authz-service

